apiVersion: v1
kind: Service
metadata:
  labels:
    app: buzzer
  name: buzzer
spec:
  type: ClusterIP
  ports:
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: buzzer