apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: buzzer
build:
  artifacts:
  - image: buzzer
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-deployment.yaml
