apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: buzzer
build:
  local:
    push: false
  artifacts:
  - image: buzzer
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-deployment.yaml
